"""PDF Settlement Assessment Report tests (Task 34).

No PDF-parsing dependency (e.g. `pypdf`) is added — Task 34 explicitly
says not to add a large dependency just for tests and that verifying
"PDF structure/content through ReportLab-generated bytes and stable
text markers" is acceptable. `services/report.py` deliberately builds
the PDF with `pageCompression=0`, so each page's text content stream is
stored uncompressed — every string drawn on the page (headings, table
cell values, disclaimer text) appears as a literal, searchable
substring in the raw PDF bytes. This is used throughout as the "PDF
text extraction" mechanism.

Run with: python -m unittest discover -s tests   (from backend/)
"""

import unittest

from fastapi import HTTPException

from app.api.report import get_settlement_report
from app.api.settlements import list_settlements
from app.schemas.decision import SettlementDecision
from app.schemas.destination import SettlementDestinationAnalysis
from app.schemas.risk import RiskAssessment
from app.services.decision import assess_settlement_decision
from app.services.destination import get_settlement_destinations
from app.services.report import ReportGenerationError, generate_settlement_report
from app.services.risk import assess_settlement_risk
from tests.fixtures import TEST_OFFICER, IsolatedDatabase


def _raw_pdf_text(pdf_bytes: bytes) -> str:
    # See module docstring: pageCompression=0 keeps content streams
    # uncompressed, so latin-1 decoding the raw bytes is sufficient to
    # search for the literal strings the report draws.
    return pdf_bytes.decode("latin-1", errors="replace")


class TestReportServiceGeneratesBhitaiMalliPdf(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls._db = IsolatedDatabase()
        cls._db.__enter__()
        bhitai_id = next(
            s.id for s in list_settlements() if s.name == "Bhitai Malli"
        )
        from app.database import get_connection
        from app.models.settlement import Settlement

        with get_connection() as conn:
            row = conn.execute(
                "SELECT * FROM settlements WHERE id = ?", (bhitai_id,)
            ).fetchone()
        cls.settlement = Settlement.from_row(row)
        cls.risk = RiskAssessment(**assess_settlement_risk(cls.settlement))
        cls.decision = SettlementDecision(
            **assess_settlement_decision(cls.settlement)
        )
        cls.destination = SettlementDestinationAnalysis(
            **get_settlement_destinations(cls.settlement)
        )
        cls.pdf_bytes = generate_settlement_report(
            cls.settlement, cls.risk, cls.decision, cls.destination
        )
        cls.text = _raw_pdf_text(cls.pdf_bytes)

    @classmethod
    def tearDownClass(cls):
        cls._db.__exit__(None, None, None)

    def test_1_report_created_successfully_and_is_substantial(self):
        self.assertIsInstance(self.pdf_bytes, bytes)
        self.assertGreater(len(self.pdf_bytes), 1000)

    def test_2_begins_with_valid_pdf_signature(self):
        self.assertTrue(self.pdf_bytes.startswith(b"%PDF-"))

    def test_3_settlement_name_appears_in_extracted_text(self):
        self.assertIn("Bhitai Malli", self.text)
        self.assertIn("Pauri Garhwal", self.text)
        self.assertIn("Uttarakhand", self.text)

    def test_4_report_title_appears(self):
        self.assertIn("VIKALP", self.text)
        self.assertIn("Settlement Evidence Assessment Report", self.text)

    def test_4b_report_explicitly_disclaims_being_an_order_or_approval(self):
        self.assertIn("not a relocation order", self.text)
        self.assertIn("government approval", self.text)

    def test_5_pending_states_are_represented(self):
        self.assertIn("pending", self.text)
        self.assertIn("not_evaluated", self.text)

    def test_6_overall_score_is_not_fabricated(self):
        self.assertIsNone(self.risk.overall_score)
        self.assertIn("Not scored", self.text)
        self.assertIn(
            "Overall risk score not computed because the complete "
            "five-dimensional assessment is not currently scoreable",
            self.text,
        )
        # Never a numeric score standing in for the real null value.
        self.assertNotIn("Overall score 0", self.text)

    def test_7_no_evidence_found_is_represented_correctly(self):
        self.assertIn("no_evidence_found", self.text)
        # Split across the two markers actually present in the PDF
        # content stream rather than one long contiguous phrase — long
        # sentences can be word-wrapped by ReportLab's Paragraph layout
        # into separate draw calls, so a single very long substring
        # search is not a stable marker (short/medium phrases are).
        self.assertIn("qualifying evidence", self.text)
        self.assertIn("scoring radius", self.text)
        self.assertIn("does not mean no hazard exists", self.text)
        # The two honest, negated disclaimer sentences the report must
        # contain — checked as the specific negation, not a bare
        # "is safe"/"risk is zero" substring search, which would also
        # (incorrectly) match inside these same correct sentences.
        # ("VIKALP does" / "not state..." fall either side of this
        # paragraph's own line wrap, confirmed against the actual
        # generated PDF bytes, so the marker starts after "does".)
        self.assertIn("not state that Bhitai Malli is safe", self.text)
        self.assertIn("does not state that landslide risk is zero", self.text)

    def test_8_decision_pathways_remain_not_evaluated(self):
        for pathway in self.decision.pathways:
            self.assertEqual(pathway.status, "not_evaluated")
        self.assertGreaterEqual(self.text.count("not_evaluated"), 3)
        self.assertIn(
            "VIKALP does not automatically recommend relocation from the "
            "current evidence",
            self.text,
        )

    def test_9_destination_candidate_absence_is_pending_not_unsafe(self):
        self.assertEqual(self.destination.candidates, [])
        self.assertIn(
            "No candidate destination data is currently available for "
            "assessment",
            self.text,
        )
        self.assertIn("Capacity assessment has not been initiated", self.text)
        # The word "unsafe" must never appear in this report.
        self.assertNotIn("unsafe", self.text.lower())

    def test_footer_and_page_numbers_present(self):
        self.assertIn("Page 1 of", self.text)
        self.assertIn("PILOT / DEMO", self.text)

    def test_no_fake_officer_identity_or_signature(self):
        self.assertIn("Not authenticated in current MVP", self.text)
        # No plausible human name should be fabricated as a signature.
        self.assertNotIn("Signed by", self.text)
        self.assertNotIn("Approved by", self.text)


class TestReportEndpoint(unittest.TestCase):
    """Part 10.10 — invalid settlement ID handling at the API layer,
    same 404 convention every other settlement-scoped endpoint uses."""

    @classmethod
    def setUpClass(cls):
        cls._db = IsolatedDatabase()
        cls._db.__enter__()

    @classmethod
    def tearDownClass(cls):
        cls._db.__exit__(None, None, None)

    def test_unknown_settlement_id_raises_404(self):
        with self.assertRaises(HTTPException) as ctx:
            get_settlement_report(999999)
        self.assertEqual(ctx.exception.status_code, 404)

    def test_valid_settlement_returns_pdf_response(self):
        bhitai_id = next(
            s.id for s in list_settlements() if s.name == "Bhitai Malli"
        )
        response = get_settlement_report(bhitai_id, officer=TEST_OFFICER)
        self.assertEqual(response.media_type, "application/pdf")
        self.assertTrue(response.body.startswith(b"%PDF-"))
        self.assertIn("Bhitai_Malli", response.headers["content-disposition"])


class TestReportGenerationErrorIsSafe(unittest.TestCase):
    def test_report_generation_error_message_has_no_internal_detail(self):
        # Confirms the error type/message contract the API route relies
        # on to avoid leaking internals (Task 34 §9) — does not force a
        # real failure (none is expected in normal operation), just
        # verifies the safe-message contract on the exception class
        # itself.
        err = ReportGenerationError("Report generation failed while building the PDF.")
        self.assertNotIn("Traceback", str(err))
        self.assertNotIn(".py", str(err))


if __name__ == "__main__":
    unittest.main()
