"""Copilot evidence layer schemas (Task 37).

These models describe a read-only snapshot of evidence that already
exists in VIKALP's risk/decision/destination/hazard-exposure services —
nothing here is a new calculation. See services/copilot.py and
docs/DECISIONS.md "Task 37" for the trust architecture this supports.
"""

from pydantic import BaseModel

from .decision import SettlementDecision
from .destination import SettlementDestinationAnalysis
from .risk import HazardExposureLandslideDetail, RiskAssessment, RiskDimensionResult

# Same disclosure text used by SettlementGeoJSONProperties (schemas/settlement.py)
# — kept in sync intentionally, not re-imported (that constant is private there).
_DEMO_PLANNING_INPUT_NOTE = "Demo planning input — source validation pending"


class CopilotSettlementSummary(BaseModel):
    settlement_id: int
    name: str
    district: str
    state: str
    population: int
    households: int
    latitude: float
    longitude: float
    data_note: str = _DEMO_PLANNING_INPUT_NOTE


class CopilotProvenance(BaseModel):
    """Distinguishes official/source-backed evidence from VIKALP's own
    derived calculations, demo planning inputs, and evidence VIKALP does
    not currently have — required for AI/officer trust (Task 37 §G)."""

    official_sources: list[str]
    derived_calculations: list[str]
    demo_planning_inputs: list[str]
    unavailable_or_missing: list[str]


class CopilotContext(BaseModel):
    """Deterministic, serializable snapshot of everything VIKALP already
    knows about one settlement. A future AI layer may read this; it may
    not write to it, and nothing here is generated by an AI model."""

    settlement: CopilotSettlementSummary
    risk_assessment: RiskAssessment
    risk_dimensions: list[RiskDimensionResult]
    hazard_exposure: HazardExposureLandslideDetail | None = None
    decision_workspace: SettlementDecision
    destinations: SettlementDestinationAnalysis
    provenance: CopilotProvenance
    limitations: list[str]
    missing_evidence: list[str]
    policy_disclaimer: str


class CopilotEvidenceItem(BaseModel):
    item: str
    value: float | int | str | None
    source: str


class EvidenceExplanation(BaseModel):
    """A "VIKALP Evidence Explanation" — a deterministic, rule-based
    summary built directly from CopilotContext values. This is NOT an
    AI prediction and NOT an AI decision; no external model is called
    to produce it (Task 37)."""

    summary: str
    evidence: list[CopilotEvidenceItem]
    missing_evidence: list[str]
    decision_status: str
    limitations: list[str]
    officer_action: str
